### ISSUE TITLE
Request: Sort the code; Point out the input file names and links

### ISSUE THREAD

**Issue by jiehuichen** [ChiLab-UCSD/Heart_MERFISH_analysis#1]
Dear ChiLab,

Your latest article is cool. I would like to use the code and data you provided to reproduce the analysis in the article so that it can be applied to my own project. 

I am confused and don't know which code is the first step and which is the second step.
Could you please sort the codes ending with ipynb?  

In addition, could you please point out the input files' names and links used by each code? Because I found that the file name used in your published code is not exactly the same as the file you actually uploaded to the public database. 

Thank you very much.

Best,
Jiehui

**Comment by Harrison-Q-Ma** [comment]
Hi Jiehui, 

Thank you for your interest in our paper. 

I have just added a README file to this repository with an explanation of the ordering of the notebooks and the location of the files. I have also changed the file names in the notebooks to match what you can download from Dryad.

Please don't hesitate to let me know if there are outstanding issues or additional questions. 

Best,
Harrison

**Comment by jiehuichen** [comment]
I appreciate it. Thanks for sharing your great work.

Best,
Jiehui
